### PR TITLE
Add support for Xiaomi Aqara Gateway Alarm

### PR DESCRIPTION
**Pull request by starkillerOG**
I am working on integrating the Xiaomi Aqara Gateway Alarm into HomeAssistant as an official component.
Since the "Xiaomi Aqara API (LAN protocol)" does not support the Alarm of the Gateway I use the "Xiaomi's miIO protocol" as implemented in your awesom library.

I know that HomeAssistant requires commans such as included in this PR to be in the upstream library instead of directly in the HomeAssistant code. That is why I want this merged in python-miio.

@rytilahti Could you please merge this PR and push to a new version of python-miio such that I can then create the PR in HomeAssistant to add official support of the Xiaomi Gateway Alarm?

Thank you in advance for your time and effort!

### CODE REVIEW

**Comment by starkillerOG** [comment]
@rytilahti is the test coverage decrease a problem?
That is the only left failed check.

**Comment by rytilahti** [comment]
Please see #470 – I think it makes sense to get that PR into a publishable state and merge it instead of adding each feature of the gateway separately.

**Comment by starkillerOG** [comment]
@rytilahti I indeed already saw #470 and I agree that if that gets merged the class in this PR schould be combined with that PR in one file.

However for HomeAssistant it probablly does not make sense to chage the xiaomi aqara integration since the "Xiaomi Aqara API (LAN protocol)" allows for subscriptions and thus events beeing pushed to HomeAssistant rather than polling the status, therfore changes are instantly seen in HomeAssistant, which is greath for automations.
I am not sure, but i think the "Xiaomi's miIO protocol" only allows for polling but not subscriptions. (although I do see somthing about listen for events in this npm package https://github.com/aholstenson/miio)

I am not planning on using any other code than the alarm_on, alarm_off and alarm_status.
I am not familliar with most of the code in PR #470, so i do not think i am the right person to clean up that PR.

Would it be possible to merge this PR that only contains the alarm class, and then later if someone has cleaned up PR #470, merge the two in one file?

**Comment by starkillerOG** [comment]
I could change the filename to "gateway.py" to be the same as in PR #470 such that the files can be merged more easily later on?

**Comment by rytilahti** [comment]
I would very much prefer it to be contained in the same PR to avoid multiple variants (see also the another PR #632). I won't be able to do a cleanup in the upcoming weeks, but considering there is some interest on that device I will do that and prepare to merge it when I can.

**Comment by starkillerOG** [comment]
@rytilahti I have moved everthing to my PR https://github.com/rytilahti/python-miio/pull/633, therefore I will close this one

**Pull request closed without merging**
