### PR TITLE
Preparation of release 0.3.6

### PR DESCRIPTION
**Pull request by syssi**
Version number bumped. Changelog updated.

### CODE REVIEW

**Comment by rytilahti** [comment]
Do you mind fixing the unit tests? Looks like some parts were merged even when those were failing.. Other than that I'm fine with a release :-)

**Comment by rytilahti** [comment]
Do you mind fixing the unit tests? Looks like some parts were merged even when those were failing.. Other than that I'm fine with a release :-)

**Comment by syssi** [comment]
I will rebase the PR. This should fix the unit tests.

**Comment by rytilahti** [comment]
Great, all green again! I'll upload a new release, thanks for taking care of all the preparations :-)

**Pull request merged**
