### PR TITLE
Add support for lumi.acpartner.mcn02

### LINKED ISSUE #637: Add support for lumi.acpartner.mcn02 please?
The most affordable Xiaomi AC Companion right now. Please add support thanks.

### PR DESCRIPTION
**Pull request by EugeneLiu**
Add support for KTBL03LM (lumi.acpartner.mcn02).

Fixes #637

### CODE REVIEW

**Comment by EugeneLiu** [comment]
@rytilahti I executed the command 'tox -e lint' locally. It's succeeded,but nothing to commit.I reapplied PR, no passing again.

**Comment by rytilahti** [comment]
Hmm, that's odd.. Anyway, the other PR (with fixes to linting) was just merged so what remains for you to do is to simply rebase this PR on top of the current master and the issue should disappear :-)

**Comment by EugeneLiu** [comment]
I find black version in .pre-commit-config.yaml different from pipline. I use 'https://github.com/psf/black' replace 'https://github.com/ambv/black' in .pre-commit-config.yaml file, so check passed. @rytilahti

**Comment by rytilahti** [comment]
Looks like the `ambv/black` forwards on github to `psf/black`, so it should be the same? Maybe the pinned version in `poetry.lock` is different?

Anyway, I think this can be merged now as the checks are passing, thanks for the PR! :tada:

**Pull request merged**
