### PR TITLE
Add miiocli support for the Air Humidifier CA1

### PR DESCRIPTION
**Pull request by syssi**

### CODE REVIEW

**Comment by syssi** [comment]
@SmaginPV Please install the branch just for testing. It introduces a special `miiocli` device called "airhumidifierca1". What's the output of:

```
miiocli -d airhumidifierca1 --ip 192.168.1.116 --token 8d503f8fe4cd0486ea235bda3d6d72bb status
```

**Comment by SmaginPV** [comment]
Works.
```
miiocli airhumidifierca1 --ip 192.168.1.116 --token 8d503f8fe4cd0486ea235bda3d6d72bb status
Power: off
Mode: OperationMode.Silent
Temperature: 23.9 °C
Humidity: 42 %
LED brightness: LedBrightness.Off
Buzzer: False
Child lock: False
Target humidity: 70 %
Trans level: None
Speed: 0
Depth: 43
Dry: True
Use time: 121210
Hardware version: 0001
Button pressed: None
```

**Comment by syssi** [comment]
Perfect!

**Comment by SmaginPV** [comment]
Thanks! Looking forward to try this in home-assistant.

**Comment by syssi** [comment]
The HA component needs to be updated slightly:

https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/fan/xiaomi_miio.py#L351

```diff
-        air_humidifier = AirHumidifier(host, token)
+        air_humidifier = AirHumidifier(host, token, model=model)
```

**Comment by syssi** [comment]
https://github.com/syssi/xiaomi_airpurifier/commit/e9766155024d5a0357a424984ab05a24f2a492a3

**Comment by SmaginPV** [comment]
Thanks @syssi. I downloaded you version of Air Humidifier custom component for hass with latest changes. I see you bumped the version of python-miio package, but didn't actually cut off this release. May I ask you please to do that? Thanks in advance!

**Comment by syssi** [comment]
The next release of python-miio will take a few days. Please be patient. :-)

**Comment by SmaginPV** [comment]
Ok, thanks, @syssi. Looking forward ;-)

**Comment by SmaginPV** [comment]
HI @syssi, Any chance to get the new release of python-miio this week?

**Comment by syssi** [comment]
I've some spare time tomorrow. May be yes. ;-)

**Pull request merged**
