### PR TITLE
Moonlight: Provide property rgb as tuple

### PR DESCRIPTION
**Pull request by syssi**

### CODE REVIEW

**Comment by syssi** [comment]
May be `set_rgb` should be improved, too and we need a method per direction? Do you prefer a name? @rytilahti

**Comment by rytilahti** [comment]
I would say we want to have it both ways, maybe just `int_to_rgb` and `rgb_to_int` to do the conversions, and changing `set_rgb` to take a tuple as an input?

**Comment by syssi** [comment]
Alright. I will care about!

**Comment by syssi** [comment]
TODO: set_rgb + miiocli compat

**Comment by syssi** [comment]
@rytilahti I'm done. :-)

**Comment by rytilahti** [comment]
Looking good! :+1:

**Pull request merged**
