### PR TITLE
Use micloud for miotspec cloud connectivity

### PR DESCRIPTION
**Pull request by rytilahti**
Convert miot_cloud to use micloud.MiotSpec for cloud accesses.
This PR also makes micloud a mandatory dependency, at least for the time being.

### CODE REVIEW

**Comment by xcraftster** [comment]
Another error occurred after I ran the command:

`$ /home/user/.local/bin/poetry run miiocli -d devtools miot-simulator --model zhimi.heater.nb1`

and then it gives me this:

`Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/user/python-miio/miio/cli.py", line 17, in <module>
    from .devtools import devtools
  File "/home/user/python-miio/miio/devtools/__init__.py", line 8, in <module>
    from .simulators import miio_simulator, miot_simulator
  File "/home/user/python-miio/miio/devtools/simulators/__init__.py", line 2, in <module>
    from .miotsimulator import miot_simulator
  File "/home/user/python-miio/miio/devtools/simulators/miotsimulator.py", line 11, in <module>
    from miio.miot_cloud import MiotCloud
  File "/home/user/python-miio/miio/miot_cloud.py", line 10, in <module>
    from micloud import MiotSpec
ModuleNotFoundError: No module named 'micloud'`

Checked micloud module and it is installed:

`Requirement already satisfied: micloud in /home/user/.local/lib/python3.8/site-packages (0.5)`

Tried it on Kubuntu desktop and Raspberry (Debian) with no success so far.

**Comment by rytilahti** [comment]
Yes, it requires that linked PR get merged and a new release prepared, but the other PR should work just fine now.

**Comment by xcraftster** [comment]
Generic means PR 1581?

> Yes, it requires that linked PR get merged and a new release prepared, but the generic miot PR should work just fine now.

**Comment by rytilahti** [comment]
> Generic means PR 1581?

Yes.

**Comment by xcraftster** [comment]
No brother, totally no luck today. Tried PR 1581 again and it says module **requests** is not there but I have it installed:

`Requirement already satisfied: requests in /home/user/.local/lib/python3.8/site-packages (2.28.1)`

Here is what it says after running the command `miiocli -d devtools miot-simulator --model zhimi.heater.nb1`:

`Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/user/python-miio/miio/__init__.py", line 50, in <module>
    from miio.integrations.genericmiot import GenericMiot
  File "/home/user/python-miio/miio/integrations/genericmiot/__init__.py", line 1, in <module>
    from .genericmiot import GenericMiot
  File "/home/user/python-miio/miio/integrations/genericmiot/genericmiot.py", line 18, in <module>
    from miio.miot_cloud import MiotCloud
  File "/home/user/python-miio/miio/miot_cloud.py", line 9, in <module>
    import requests  # TODO: externalize HTTP requests to avoid direct dependency
ModuleNotFoundError: No module named 'requests'`

> > Generic means PR 1581?
> 
> Yes.

**Comment by xcraftster** [comment]
Ok, I managed to go further but after I installed module **requests** in poetry shell. Now it says **model-to-urn.json** is missing:

Command:
`/home/user/.local/bin/poetry run miiocli -d devtools miot-simulator --model zhimi.heater.nb1`

Output:
`DEBUG:miio.miot_cloud:Going to download http://miot-spec.org/miot-spec-v2/instances?status=all to /home/user/.cache/python-miio/model-to-urn.json
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): miot-spec.org:80
DEBUG:urllib3.connectionpool:http://miot-spec.org:80 "GET /miot-spec-v2/instances?status=all HTTP/1.1" 307 241
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): miot-spec.org:443
DEBUG:urllib3.connectionpool:https://miot-spec.org:443 "GET /miot-spec-v2/instances?status=all HTTP/1.1" 200 None
ERROR:miio.click_common:Exception: [Errno 2] No such file or directory: '/home/user/.cache/python-miio/model-to-urn.json'
Traceback (most recent call last):
  File "/home/user/python-miio/miio/click_common.py", line 54, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/.cache/pypoetry/virtualenvs/python-miio-Po5YGcTv-py3.8/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/user/.cache/pypoetry/virtualenvs/python-miio-Po5YGcTv-py3.8/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/.cache/pypoetry/virtualenvs/python-miio-Po5YGcTv-py3.8/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/.cache/pypoetry/virtualenvs/python-miio-Po5YGcTv-py3.8/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/.cache/pypoetry/virtualenvs/python-miio-Po5YGcTv-py3.8/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/user/python-miio/miio/devtools/simulators/miotsimulator.py", line 218, in miot_simulator
    dev = SimulatedDeviceModel.parse_raw(cloud.get_model_schema(model))
  File "/home/user/python-miio/miio/miot_cloud.py", line 69, in get_model_schema
    instances = self.fetch_release_list()
  File "/home/user/python-miio/miio/miot_cloud.py", line 83, in fetch_release_list
    data = self._fetch(url, self._cache_dir / mapping_file)
  File "/home/user/python-miio/miio/miot_cloud.py", line 109, in _fetch
    written = target_file.write_text(response)
  File "/usr/lib/python3.8/pathlib.py", line 1255, in write_text
    with self.open(mode='w', encoding=encoding, errors=errors) as f:
  File "/usr/lib/python3.8/pathlib.py", line 1222, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/usr/lib/python3.8/pathlib.py", line 1078, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/.cache/python-miio/model-to-urn.json'`

**Comment by rytilahti** [comment]
Try creating the directory `mkdir -p /home/user/.cache/python-miio/` and retry (looks like I forgot to create the directory if it doesn't exist already), but please let's move this discussion to the other issue as this is not directly related to this micloud conversion PR.

**Pull request merged**
