### PR TITLE
Powerstrip support improved

### PR DESCRIPTION
**Pull request by syssi**
New properties and commands added: wifi_led, power_price.

@rytilahti Could you provide a response example for

```
mirobo raw_command get_prop "['power', 'temperature', 'current', 'mode', 'power_consume_rate', 'wifi_led', 'power_price']"
```

Thanks!

### CODE REVIEW

**Comment by rytilahti** [comment]
```
Sending cmd get_prop with params ['power', 'temperature', 'current', 'mode', 'power_consume_rate', 'wifi_led', 'power_price']
['on', 48.7, 0.05, None, 4.09, 'on', 49]
```

Thanks for extending the support :-)

**Comment by syssi** [comment]
Could you try to set a float?

```
mirobo raw_command set_power_price "['49.51']"
mirobo raw_command get_prop "['power_price']"
```

**Comment by syssi** [comment]
```
mirobo info
```
would be interesting also. Do you have the 1st or 2gen of the powerstrip?

**Comment by rytilahti** [comment]
It accepts floats, but rounds them down:
```
set_power_price "[48.51]"
Sending cmd set_power_price with params [48.51]
['ok']

Sending cmd get_prop with params ['power_price']
[48]
```
Values with quotes is not accepted and will result in `Error: {'code': -5001, 'message': 'params err'}`.
Maximum value is 999.

This is the v2 of zimi:
```
{'result': 
  {'token': '8523aaa7d78c8fb6eXXXX', 'mac': '28:6C:07:XX:XX:XX', 
   'ap': {'ssid': 'HomeNet', 'bssid': 'C2:6E:1F:XX:XX:XX', 'rssi': -61}, 
   'ott_stat': [0, 240086, 236, 0], 'hw_ver': 'MW300',
   'netif': {'gw': '192.168.250.1', 'localIp': '192.168.XX.XX', 'mask': '255.255.255.0'}, 'life': 903289,
   'otu_stat': [0, 0, 0, 0, 0, 0], 'fw_ver': '1.2.4_50', 'model': 'zimi.powerstrip.v2', 'cfg_time': 0, 'wifi_fw_ver': 'SD878x-14.76.36.p84-702.1.0-WM', 'mmfree': 15408
},
```

**Pull request merged**
