### PR TITLE
Added support for Xiaomi Smart Space Heater 1S (zhimi.heater.mc2a)

### PR DESCRIPTION
**Pull request by paranerd**
This PR adds support for Xiaomi Smart Space Heater 1S (zhimi.heater.mc2a).
Changes are minimal as the mc2a is basically identical to the mc2.

I own the device myself and can confirm that everything reads and performs as expected.

I would appreciate a quick merge as this is only the first step on my journey to natively integrate both devices into the main "Xiaomi" integration for Home Assistant.

Thanks a lot for the amazing foundation!

### CODE REVIEW

**Comment by paranerd** [comment]
Getting a linting error "`miio/integrations/dmaker/fan/fan_miot.py:314: error: Incompatible types in assignment (expression has type "dict[str, object]", base class "MiotDevice" defined the type as "dict[str, dict[str, dict[str, Any]]]")  [assignment]`"

The error itself makes sense to me, because the types indeed seem incompatible. However I didn't edit that specific line, so not sure how to fix it.

**Review by rytilahti — CHANGES_REQUESTED** [review]
Ohh, please split the PR into two, one per each device.

**Comment by paranerd** [comment]
I removed the p39 code and merged the recent changes into my branch but for some reason now `macos-latest` and `windows-latest` CI checks seem to be randomly failing - any ideas?

**Review by rytilahti — APPROVED** [review]
Those are known to be flaky, no worries on that :-)

**Pull request merged**
