### PR TITLE
Add support for fanspeeds of Roborock E2 (E20/E25)

### PR DESCRIPTION
**Pull request by tribut**
This adds the fan speed names as reported by the official app for the Roborock E2.

Cf. https://github.com/rytilahti/python-miio/pull/468#issuecomment-515897609

### CODE REVIEW

**Comment by tribut** [comment]
Alright, updated PR accordingly.

**Comment by rytilahti** [comment]
Looks good! Please run `tox -e lint` to make the tests pass. Also, if you want to hold the original namings, you could add a comment for the enum.

**Comment by tribut** [comment]
Updated and rebased.

**Comment by rytilahti** [comment]
Thanks :tada:

**Pull request merged**
