### PR TITLE
Use asyncio facilities for push server where possible

### PR DESCRIPTION
**Pull request by starkillerOG**
Make the push server fully async by avoiding using executors when not necessary.

As required by https://github.com/home-assistant/core/pull/64726

### CODE REVIEW

**Comment by starkillerOG** [comment]
@rytilahti I tested this and everything still works.
This makes a clearer seperation between sync and async code by making all push_server functions async.

Can you merge this?

**Comment by starkillerOG** [comment]
@rytilahti could you please merge this so I can move allong with PR https://github.com/home-assistant/core/pull/64726?

**Review by rytilahti — APPROVED** [review]
LGTM on surface and it is much better this way, so let's get this merged. Thanks! :+1:

**Comment by starkillerOG** [comment]
@rytilahti thanks a lot!
Could you let me know when a new python-miio version is released so I can continue with the HomeAssistant PR?

**Comment by rytilahti** [comment]
I'm currently on holidays so I'm not feeling comfortable creating a new release just right now, especially as the current code base contains lot of changes related to #1495 that should be tested also on other devices that I have in my possession.

I'll try to find some time to review the related homeassistant PR soon though :-)

**Pull request merged**
