### PR TITLE
Add basic dmaker.fan.p11 support

### PR DESCRIPTION
**Pull request by syssi**
I'm trying to get this fan supported in 0.5.4 already.

### CODE REVIEW

**Comment by iquix** [comment]
I own this fan model (dmaker.fan.p11), and it seems that 'status' siid:2, piid:6 is actually fan speed of level 1~100
I have already tested this, with swim2sun's code.

Therefore, line #50 of fan_miot.py should be
"fan_speed": {"siid": 2, "piid": 6},

Thank you.

**Comment by syssi** [comment]
@iquix Thanks for you support! I will fix the issue right away.

**Comment by syssi** [comment]
@iquix Could you provide the model no. your of device? I want to use it here soon: https://github.com/syssi/xiaomi_airpurifier#supported-devices

**Comment by iquix** [comment]
The brand is mijia and the model no. is BPLDS03DM.
Thank you so much.
https://www.google.com/search?q=mijia+BPLDS03DM

**Pull request merged**
