### PR TITLE
Improve the support of the Air Humidifier CA1 (Closes: #383)

### PR DESCRIPTION
**Pull request by syssi**

### CODE REVIEW

**Comment by SmaginPV** [comment]
Hi. Is it possible to create the release with this PR included? Thanks in advance.

**Comment by syssi** [comment]
@SmaginPV Are you able to test these changes?

**Comment by SmaginPV** [comment]
Yah, just thought about it after left the comment. I did the install of this package from the repo with 
python3 setup.py install
Then I tried to turn on the device and it works.
Then tried to fetch the status, but see the same 'UART timeout' error
```
miiocli -d airhumidifier --ip 192.168.1.116 --token 8d503f8fe4cd0486ea235bda3d6d72bb status
INFO:miio.cli:Debug mode active
DEBUG:miio.protocol:Unable to decrypt, returning raw bytes: b''
DEBUG:miio.device:Got a response: Container:
    data = Container:
        data = b'' (total 0)
        value = b'' (total 0)
        offset1 = 32
        offset2 = 32
        length = 0
    header = Container:
        data = b'!1\x00 \x00\x00\x00\x00\x03\xb8,V\x00\n\xd8\x8f' (total 16)
        value = Container:
            length = 32
            unknown = 0
            device_id = b'\x03\xb8,V' (total 4)
            ts = 1970-01-09 05:26:39
        offset1 = 0
        offset2 = 16
        length = 16
    checksum = b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' (total 16)
DEBUG:miio.device:Discovered 03b82c56 with ts: 1970-01-09 05:26:39, token: b'00000000000000000000000000000000'
DEBUG:miio.device:192.168.1.116:54321 >>: {'id': 1, 'method': 'miIO.info', 'params': []}
DEBUG:miio.device:192.168.1.116:54321 (ts: 1970-01-09 05:26:39, id: 1) << {'result': {'life': 710799, 'token': '8d503f8fe4cd0486ea235bda3d6d72bb', 'mac': '34:CE:00:BB:D2:9E', 'fw_ver': '1.5.6', 'hw_ver': 'MTK7697', 'uid': '1583099850', 'model': 'zhimi.humidifier.ca1', 'mcu_fw_ver': '1024', 'wifi_fw_ver': '4.3.0', 'ap': {'rssi': -39, 'ssid': 'Cherry', 'bssid': '50:46:5D:93:52:48'}, 'netif': {'localIp': '192.168.1.116', 'mask': '255.255.255.0', 'gw': '192.168.1.1', 'gw_mac': '50:46:5D:93:52:4C'}, 'mmfree': 68712}, 'id': 1}
DEBUG:miio.device:192.168.1.116:54321 >>: {'id': 2, 'method': 'get_prop', 'params': ['power', 'mode', 'temp_dec', 'humidity', 'buzzer', 'led_b', 'child_lock', 'limit_hum', 'use_time', 'hw_version', 'trans_level', 'button_pressed']}
DEBUG:miio.device:192.168.1.116:54321 (ts: 1970-01-09 05:26:42, id: 2) << {'error': {'code': -9999, 'message': 'UART timeout'}, 'id': 2}
DEBUG:miio.click_common:Exception: {'code': -9999, 'message': 'UART timeout'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/python_miio-0.4.2-py3.6.egg/miio/click_common.py", line 54, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/python_miio-0.4.2-py3.6.egg/miio/click_common.py", line 262, in wrap
    kwargs['result'] = func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/python_miio-0.4.2-py3.6.egg/miio/click_common.py", line 229, in command_callback
    return miio_command.call(miio_device, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/python_miio-0.4.2-py3.6.egg/miio/click_common.py", line 191, in call
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/python_miio-0.4.2-py3.6.egg/miio/airhumidifier.py", line 295, in status
    values.extend(self.send("get_prop", _props[:_props_per_request]))
  File "/usr/local/lib/python3.6/site-packages/python_miio-0.4.2-py3.6.egg/miio/device.py", line 270, in send
    raise DeviceError(m.data.value["error"])
miio.exceptions.DeviceError: {'code': -9999, 'message': 'UART timeout'}
Error: {'code': -9999, 'message': 'UART timeout'}
```

**Comment by SmaginPV** [comment]
What's interesting, is that get_prop with just single parameter works:
```
iiocli -d airhumidifier --ip 192.168.1.116 --token 8d503f8fe4cd0486ea235bda3d6d72bb raw_command get_prop "['humidity']"
INFO:miio.cli:Debug mode active
Running command raw_command
DEBUG:miio.protocol:Unable to decrypt, returning raw bytes: b''
DEBUG:miio.device:Got a response: Container:
    data = Container:
        data = b'' (total 0)
        value = b'' (total 0)
        offset1 = 32
        offset2 = 32
        length = 0
    header = Container:
        data = b'!1\x00 \x00\x00\x00\x00\x03\xb8,V\x00\n\xdb\xfb' (total 16)
        value = Container:
            length = 32
            unknown = 0
            device_id = b'\x03\xb8,V' (total 4)
            ts = 1970-01-09 05:41:15
        offset1 = 0
        offset2 = 16
        length = 16
    checksum = b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' (total 16)
DEBUG:miio.device:Discovered 03b82c56 with ts: 1970-01-09 05:41:15, token: b'00000000000000000000000000000000'
DEBUG:miio.device:192.168.1.116:54321 >>: {'id': 1, 'method': 'get_prop', 'params': ['humidity']}
DEBUG:miio.device:192.168.1.116:54321 (ts: 1970-01-09 05:41:15, id: 1) << {'result': [45], 'id': 1}
[45]
```

**Comment by rytilahti** [comment]
Can you try if `get_prop` works with two, three and so on, or is it just working with a single one? Anyway, the fix @syssi just merged limits the amount of properties to be requested to one, so either you are not using the updated code or there is some other issue there.

**Comment by syssi** [comment]
`miiocli airhumidifier` uses the default implementation. The CA1 code path isn't used.

**Comment by SmaginPV** [comment]
> `miiocli airhumidifier` uses the default implementation. The CA1 code path isn't used.

That means I can't test you change with miiocli, or I need to use some additional option?

**Comment by SmaginPV** [comment]
Ok, got your latest change from feature/airhumidifier-ca1-cli and it works!!

```
miiocli airhumidifierca1 --ip 192.168.1.116 --token 8d503f8fe4cd0486ea235bda3d6d72bb status
Power: off
Mode: OperationMode.Silent
Temperature: 23.9 °C
Humidity: 42 %
LED brightness: LedBrightness.Off
Buzzer: False
Child lock: False
Target humidity: 70 %
Trans level: None
Speed: 0
Depth: 43
Dry: True
Use time: 121210
Hardware version: 0001
Button pressed: None
```

**Pull request merged**
