### PR TITLE
Reformat history data if returned as a dict/Roborock S7 Support (#989)

### LINKED ISSUE #989: Roborock S7
Before submitting a new request, use the search to see if there is an existing issue for the device.

**Device information:**

  - Name(s) of the device: Roborock S7
  - Link: https://hejdom.pl/blog/11-xiaomi/465-odkurzacz-xiaomi-roborock-s7.html

Use `miiocli device --ip <ip address> --token <token>`.

  - Model: roborock.vacuum.a15

**Additional context**
If you know already about potential commands or any other useful information to add support for the device, please add that information here.

What do you need to add this vaacum?

### PR DESCRIPTION
**Pull request by fettlaus**
This should fix #989 by taking care of the new history format, the Roborock S7 is using. I also added some tests just in case. Couldn't find anything else not working with this vacuum so maybe that was all it takes for it to be supported.

I would've used some pull request template but it seems there isn't any so there is that.

### CODE REVIEW

**Review by rytilahti — APPROVED** [review]
LGTM, thanks for the PR! Could you add the S7 to the list of supported devices in the README.md?

**Comment by vukisz** [comment]
When this will be available to test?

**Comment by micke** [comment]
Would it be possible to release a new version of this library so that HA and others can update with support for the S7? 🥇

**Comment by rytilahti** [comment]
It hasn't been that much since the last release, so this will need to wait a bit as I want to have at least some WIP PRs merged before I spend some time to do release preparation.

There is also #992 that is related, but I haven't managed to test nor review that yet.

**Comment by StefanSarzio** [comment]
So there is a fix, it's just not being deployed?

Teemu R. ***@***.***> schrieb am Do., 8. Apr. 2021, 01:01:

**Comment by rytilahti** [comment]
Yes, there has been no releases with this fix so far. After a new release it will still require a version bump to homeassistant (assuming you are using it), otherwise you could simply use the git version of the library in the meanwhile.

**Comment by andybali** [comment]
I update core today. Still Error by adding S7

`xiaomi_miio: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 407, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 516, in async_device_update
    await task
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/xiaomi_miio/vacuum.py", line 499, in update
    self.last_clean = self._device.last_clean_details()
  File "/usr/local/lib/python3.8/site-packages/miio/vacuum.py", line 381, in last_clean_details
    if not history.ids:
  File "/usr/local/lib/python3.8/site-packages/miio/vacuumcontainers.py", line 214, in ids
    return list(self.data[3])
KeyError: 3`

**Comment by rytilahti** [comment]
Are you sure you are running 2021.5.1 that just got released today? The fix was confirmed to work in a homeassistant issue just few moments ago.

**Comment by vukisz** [comment]
After this update started working for me.

**Comment by andybali** [comment]
Sorry, I am running 2021.5.0

**Pull request merged**
