### PR TITLE
Add ability to read IP and token from config file

### PR DESCRIPTION
**Pull request by skorokithakis**
I don't like env vars, so I added a simple config file using ConfigParser. The script will prefer the vars (or command line options) as usual, but it will read the config file as a last resort.

### CODE REVIEW

**Comment by skorokithakis** [comment]
Ah, right. Feel free to close, I just quickly hacked it together because I don't like env vars and figured I'd issue a PR. No problem!

**Comment by skorokithakis** [comment]
By the way, you might want to add a link to the docs somewhere, currently they're not linked anywhere.

**Comment by syssi** [comment]
Thanks for your appreciation!

**Comment by rytilahti** [comment]
I added a link to README.rst and removed README.md, so now there's a link! @skorokithakis if you want, we can merge the config parser part for now and get rid of it later on, when I get some time to look into making it properly.

**Comment by skorokithakis** [comment]
Up to you man, you're the maintainer. The code can be removed easily, but changing the configuration file is harder. If you think you'll keep the same config file in the future, I would merge, otherwise I would either hold off or try to get the config format right at this time so I didn't have to tell everyone to change later on.

**Pull request closed without merging**
