### PR TITLE
add method to load subdevices from dict (EU gateway support)

### PR DESCRIPTION
**Pull request by starkillerOG**

### CODE REVIEW

**Review by rytilahti — APPROVED** [review]
LGTM, let's get this in for the next release! :+1:

**Comment by carloslindo** [comment]
@rytilahti @starkillerOG Sorry if my question is a stupid one, but I would like to know how long it normally takes or what are the next steps in the process since this PR is merged into master until the code is available in the Xiaomi Miio integration in Home Assistant.

Thank you

**Comment by rytilahti** [comment]
In this specific case, the situation is a bit more complex as it will require some more integration work. That being said, I'll try to find some time soonish (upcoming weekend, or the one after that, I'm currently busy with other responsibilities) to prepare a release.

@starkillerOG is currently doing great work on improving the homeassistant integration to use config flows which will be helpful for integrating this, too!

**Comment by carloslindo** [comment]
Thank you for the update

**Comment by carloslindo** [comment]
After release 0.5.5 how long does it normally take to get the latest code in the Xiaomi Miio integration in Home Assistant?

**Comment by starkillerOG** [comment]
@carloslindo the 0.5.5 version is already merged in the dev release of HomeAssistant.
I just started writing the code for the options flow to let the user use the EU gateway with miio-cloud

**Comment by starkillerOG** [comment]
@carloslindo I just made the PR for homeassistant: https://github.com/home-assistant/core/pull/47955

If you could try it out, that would be greath!

I will start testing it myself in the coming days.

**Comment by carloslindo** [comment]
@starkillerOG You mean after it gets released in the home-assistant core? Or can I try it from a dev release?

**Comment by starkillerOG** [comment]
@carloslindo you can download the files from the linked PR, then run it as a custom component.
Will test myself a bit and then put some instructions here: https://github.com/rytilahti/python-miio/issues/728

**Comment by carloslindo** [comment]
@starkillerOG Thank you. I will help with testing!

**Pull request merged**
