### PR TITLE
create separate directory for yeelight

### PR DESCRIPTION
**Pull request by Kirmas**
Based on https://github.com/rytilahti/python-miio/pull/1094#pullrequestreview-769683812 but I believe the "moving" PR could be separate. This PR only move the yeelight code to the folder. Next PR will be soon.

@rytilahti could you merge this one?

### CODE REVIEW

**Comment by Kirmas** [comment]
> Let's move it under `integrations/yeelight/` and use absolute imports, this way:
> 
> 1. the integrations are clearly separated from the main miio code-base, and
> 2. it will be easier to add support for out-of-tree integrations, when all integrations are self-contained

@rytilahti Did I do this correct? Could you provide what else I must change? Maybe move test some how.

**Comment by rytilahti** [comment]
> @rytilahti Did I do this correct? Could you provide what else I must change? Maybe move test some how.

Looking good, but yeah, the test should also be moved under `tests/` inside the integration directory. Could you try if it still get executed fine after moving it? I think pytest should find it still just fine, and If not, we'll need to figure out how to adjust the test collection. The test itself should probably use a relative import for the module under test, and absolute imports just for modules that are contained under `miio` or `miio.tests`.

**Comment by rytilahti** [comment]
@Kirmas the integrations should be inside the miio package so that it will be accessible. Now running `pytest miio` works fine at least for me :-)

**Comment by rytilahti** [comment]
Yes, I think we can merge this now. Thanks for the PR and pushing this onward :-)

**Pull request merged**
