### PR TITLE
Add support for Scishare coffee maker (scishare.coffee.s1102)

### LINKED ISSUE #358: Rockrobo firmware 3.3.9_003254
Anyone has upgraded and can confirm nothing breaks?

### LINKED ISSUE #833: Add support for xiaomi scishare coffee machine
@rytilahti  Is it possible to integrate[ xiaomi scishare coffee machine](https://www.banggood.com/SCISHARE-S1103-SCISHARE-Smart-Automatic-Capsule-Coffee-Machine-Extraction-Electric-Coffee-Maker-Kettle-From-Xiaomi-Youpin-p-1291120.html?gmcCountry=IT&currency=EUR&createTmp=1&utm_source=googleshopping&utm_medium=cpc_bgs&utm_content=xibei&utm_campaign=xibei-ssc-it-en-all-newcustom-nca50-0628&gclid=Cj0KCQjwt4X8BRCPARIsABmcnOpfiFDcRvXetGi4xf9TvMfzDKwPsy5Xjfc0KhGDVnEjjKgnn0kNEVwaAtPmEALw_wcB&cur_warehouse=CN) in home assistant ? I tried with raw miio commands and it seems to work. thank you

Model: scishare.coffee.s1102
Hardware version: esp8266
Firmware version: 2.1.0

https://github.com/aholstenson/miio/issues/284
[](https://github.com/aholstenson/miio/issues/284)

### PR DESCRIPTION
**Pull request by rytilahti**
First steps to implement and close #833

TBD:
* Status codes are unknown
* Tests

### CODE REVIEW

**Comment by matteos1** [comment]
as soon as possible i test the Scishare coffee maker

**Comment by matteos1** [comment]
There are some news? Is implemented in 0.118? Thank you

**Comment by syssi** [comment]
@matteos1 Did you test this implementation?

**Comment by matteos1** [comment]
i have tested and it seems to work.

**Comment by matteos1** [comment]
@syssi to test the file inside the custom component, I create a xiaomi_scishare folder, and insert __init__.py and scishare_coffeemaker.py (https://github.com/rytilahti/python-miio/pull/858/commits/d188100fd764d430773de1372e8a460cf1554970)? what is the name of the platform to insert in the configuration.yaml, naturally with the attributes name, host, token?

**Comment by matteos1** [comment]
is it possible now to make scishare work with home hassistant?

**Comment by rytilahti** [comment]
Yes, it is possible but will require someone to do the integration. Also, at the moment it's still under discussion how "cookers" are to be exposed to homeassistant: https://github.com/home-assistant/architecture/discussions/501 .

**Comment by khmelevskikh** [comment]
Hi guys,
Commands with params doesn't work for me by some reason:
boil_water 300 90
Boiling 300 ml water (90C)
False
Raw commands for the same works fine

**Comment by rytilahti** [comment]
@khmelevskikh could you please open an issue for that, and potentially include the commands you tried (with `--debug` to get the raw payloads)? Sounds like there is issue with the type conversion somewhere.

**Pull request merged**
