### PR TITLE
Add GPLv3 license

### PR DESCRIPTION
**Pull request by pluehne**
I just packaged [`python-miio` for Arch Linux in the Arch User Repository](https://aur.archlinux.org/packages/python-miio/).

In doing so, I noticed that, while the GLPv3 license is [stated in `setup.py`](https://github.com/rytilahti/python-miio/blob/5f4e8b139aa302375a6e870ca201644bb92d91c2/setup.py#L15), there is no explicit license file. I know that dealing with licenses is somewhat annoying, but proper packages should install license files to `/usr/share/licenses/`. Additionally, this is useful information for users, and the GLPv3 license will be displayed nicely by GitHub for clarity.

I took the license template from [GLPv3 in Markdown](https://github.com/TheFox/GPLv3.md) and filled in the necessary information in the second commit, 18fdce146e51f53c7abdde8fb9697d80d98c583e, to make reviewing the actual changes more easy.

Feel free to make adjustments as necessary 😃.

### CODE REVIEW

**Comment by rytilahti** [comment]
Well spotted, and it is indeed a good idea to have an explicit LICENSE file delivered with the package (needs adjusting also to setup.py? I'm unsure..). However, I think it makes more sense to have a verbatim copy of original, text-based (non-markdownized) version of the license to make it plain enough. What do you think?

**Comment by pluehne** [comment]
That’s up to you, after all this project is mostly your effort 😃.

I usually prefer Markdown license files, because they are easier on the eye should you really want to read them. And even if nobody looks at the license file, why not make it look nicer?

**Comment by pluehne** [comment]
Aside from my earlier comment, I think that naming it `LICENSE.md` is fine. My understanding is that most systems will look for any variations like `LICENSE`, `COPYING`, `LICENSE.txt`, `LICENSE.md`, etc.

And I don’t know what the convention for handling licenses in `setup.py` is, as I’m haven’t build Python install scripts so far.

**Comment by rytilahti** [comment]
https://stackoverflow.com/questions/9977889/how-to-include-license-file-in-setup-py-script makes a remark that using a metadata for pointing out the license is fine, so I don't think it's necessary to ship the license file with it. Let's ship the LICENSE.md for those who want to have it available, the verbatim copy of the license is available anyway e.g. in https://www.gnu.org/licenses/gpl-3.0.en.html . Thanks again!

**Comment by rytilahti** [comment]
I added also a verbatim copy of the license in text as provided by github's "add license file" feature. It doesn't seem to show the license on the front page as of yet, maybe it's something that gets added at some point after some sort of analysis procedure is run on the repo..

**Comment by pluehne** [comment]
@rytilahti: I’m curious about the new release 😃. Is there anything left to do for 0.3.2 that I could help with?

**Comment by rytilahti** [comment]
@pluehne I think the only thing to do for a new release would be updating the README to contain a link to the new documentation (and updating the documentation where necessary!). If you want to contribute, a read-through & updates to the docs would be more than welcome :-)

The preliminary docs are now available in https://python-miio.readthedocs.io/en/latest/ - a local copy can be compiled just by calling `make` inside docs directory. My plan was to have it in such a state that it could be e.g. linked inside homeassistant's documentation instead of duplicating the information (see https://home-assistant.io/components/vacuum.xiaomi_miio/#retrieving-the-access-token).

**Comment by pluehne** [comment]
@rytilahti: Cool 🙂! Unfortunately, I’m very busy until the weekend, so maybe, I’ll have a look at the docs then. Would that be fine?

**Comment by rytilahti** [comment]
That'd we awesome, thanks :-)

**Pull request merged**
