### PR TITLE
Initial support for xiaomi gateway devices

### PR DESCRIPTION
**Pull request by rytilahti**
This adds preliminary support for Xiaomi Aqara gateway devices. Currently implemented interfaces include controlling the alarm and the light facilities, as well as some other miscellaneous features.

Thanks to @approximatenumber and @starkillerOG for pushing to make this happen :tada:

--- 

This has been rotting on my computer for over a year, so I thought I'd just push this up in case someone wants to work on it - personally I'm not going to do that as I'm using zigbee2mqtt to control my xiaomi devices. The code does not work without modifications, but gives at least a starting point to build upon.

Related to https://github.com/home-assistant/home-assistant/pull/20294

### CODE REVIEW

**Comment by approximatenumber** [comment]
Great job! Yesterday I was upset about unsupported gateway and decided to write my own bindings, but it's cool that I've found a ready to use solution :)

**Comment by starkillerOG** [comment]
@rytilahti can this be merged?
Or schould I try to clean it up a bit more, or do you have time to clean it up?

**Comment by rytilahti** [comment]
I'm waiting for #634 to be merged before doing the next (0.50!) release, just to avoid pushing two releases out in so short order. I'm hoping it will be done soon enough, but feel free to add cleanup PRs if you like! Otherwise I will do it when we are nearing the release.

**Comment by rytilahti** [comment]
@approximatenumber I moved the light controls underneath a "subdevice" accessible under `light` property.

@starkillerOG do you mind giving this a test and say OK if it's okay to merge this now, thanks!

**Comment by starkillerOG** [comment]
@rytilahti thanks, looks good!
I will test it tommorrow and let jou know

**Comment by hoangphison** [comment]
hello @rytilahti 
does this PR will support aqara homekit gateway?

**Comment by rytilahti** [comment]
No idea, to be honest. This was based on some very old code for the first or second gen gateway (with the developer mode to be used with https://github.com/Danielhiversen/PyXiaomiGateway) which was sold in a kit several years ago.

**Comment by starkillerOG** [comment]
@rytilahti I have just tested the Alarm class and it works perfectly!
Thank you so much for your help!
This PR can now be merged I think.

**Pull request merged**
