### PR TITLE
Add consumable status to viomi vacuum

### PR DESCRIPTION
**Pull request by titilambert**
Tested with:
Model: viomi.vacuum.v7
Hardware version: Linux
Firmware version: 3.5.3_0047

### CODE REVIEW

**Review by rytilahti — APPROVED** [review]
Looks good to me, thanks for the PR! :+1: This can be merged after the checks are passing.

**Comment by titilambert** [comment]
@rytilahti I fixed the tests in my changes, but the tests are broken in master. What should I do ?

**Comment by rytilahti** [comment]
@titilambert oops, I didn't notice prior merging that the lastly merged PR broke linting.. I think the best way to proceed is to incorporate the linting fixes to this PR, so please run `tox -e lint` locally and add the modified files to this PR, thanks!

**Comment by titilambert** [comment]
> @titilambert oops, I didn't notice prior merging that the lastly merged PR broke linting.. I think the best way to proceed is to incorporate the linting fixes to this PR, so please run `tox -e lint` locally and add the modified files to this PR, thanks!

OK ! I just fix the lint, the code coverage decreased, is it fine ?

**Comment by rytilahti** [comment]
Decrease in code coverage is not that big issue, although it'd be great to have tests for these parts. Let's get this merged so that the PR I linked can be rebased on top of this, thanks again for the PR!

**Pull request merged**
