### PR TITLE
add AqaraWallOutlet support

### PR DESCRIPTION
**Pull request by starkillerOG**
see issue https://github.com/rytilahti/python-miio/issues/650

### CODE REVIEW

**Comment by starkillerOG** [comment]
@rytilahti can you also merge this?

**Comment by rytilahti** [comment]
Looks good to me, but if it's fine for you, we could wait until we also know the control commands so that they can be added in a single PR?

**Comment by starkillerOG** [comment]
yea that is fine, was just pushing fast to see if I could get it in 0.5.1, but since that is already out, lets indeed wait for the controll commands.

**Comment by rytilahti** [comment]
Yeah, when the prepare release PR hits the master, the release is already "done" at that point. I could have waited out for a bit, but as I had some free time I thought it'd be a good idea to make a quick release to unblock some downstream PRs.

**Comment by starkillerOG** [comment]
@rytilahti this has been comfirmed to work by @miway80, So this can now be merged.
Both getting status and controlling the device is implemented.

**Pull request merged**
