### PR TITLE
WIP: improve miotdevice API, add gosund plug support (cuco.plug.cp1)

### PR DESCRIPTION
**Pull request by rytilahti**
This PR aims to add better support for miot devices, and build a common API to simplify contributions for new devices.

* add miot_info() to get the common information from the device
  * this includes manufacturer, model, firmeware version and serial number

* add get_properties_for_dataclass(cls) which allows easy implementation for get_properties mappings
  * each field() can define metadata containing siid and piid, these are mapped automatically to the response container
  * _siid can be used to define common siid, _max_properties can be used to set number of maximum properties per request

* "old" get_properties_for_mapping() requires explicit passing of the mapping, no more passing over `__init__`

* rename old set_property to set_property_from_mapping
    * add set_properties_from_dataclass (allows passing a mapping object with all wanted values at once)
    
    ```
    device.set_properties_from_dataclass(GosundPlugStatus(state=True, some_other_property=123)
    ```
    
    * new set_property helper which takes kwargs that are used automatically with the help of the class-given _MAPPING:
    
    ```
    device.set_property(state=True)
    ```

* Add support for gosund miot plug (cuco.plug.cp1) to show how the API could work.

## TODO
* Naming of helper methods, `_MAPPING`
* Unit tests for all MiotDevice interfaces
* Split set property requests based on `_max_properties`.
* python 3.6 compatibility (dataclasses are available only python 3.7+)
* helper to create fields with wanted metadata, maybe `add_property(piid, siid)`?
* document the API, figure out the best way to do conversions, if needed.
* handling read-only/write-only properties
* common API for actions

### CODE REVIEW

**Comment by rytilahti** [comment]
@foxel if you have some time, your feedback on how/if the API needs adaptations to allow porting airpurifier_miot over it :-) for the time being this is just an experimental try to see if this approach makes sense in general, alas, the only miot device I have has only a single service (besides the common miot_info) with a single property...

**Comment by marcelrv** [comment]
FYI.
For the zhimi.airpurifier.mb3  all siids respond with value exept for siid 1. siid1 does not respond to get_properties so below ones are not available in reality but are in the spec file.

Device Information-Current Firmware Version
Device Information-Device Manufacturer
Device Information-Device Model
Device Information-Device Serial Number

**Comment by rytilahti** [comment]
Yeah, probably not all manufacturers implement it properly (considering miio.info also reveals enough information). Here's what I'm getting out with that plug:
```
MiotInfo(manufacturer='hello', model='hello', serial_number='hello', firmware_version='hello')
```

**Comment by xuefer** [comment]
the code looks much easier for miot in this branch, can you improve it asap? i want to add more devices like curtain wifi version
i wonder if someone already modify devtools/miottemplate.py to generate for new miio.miot_device class instead of for non-existing miio.MiOTService class

**Comment by rytilahti** [comment]
I'll try to find some time soonish to push this onwards. I have a locally modified devtools that will make integrating a bit easier. I'll create another PR for that when I can.

**Comment by mkohns** [comment]
Hi. Just an idea: What about downloading and parsing the miot spec on new device detection? On this page:
https://home.miot-spec.com/s/<model>
the spec JSON can be retrieved. With a small parser the full device feature set could be utilized.

**Comment by rytilahti** [comment]
@mkohns see the soon-to-be-linked PR, I'm closing this now as obsolete :-)

**Pull request closed without merging**
