### PR TITLE
Make discovery to work with no IP addr and token, courtesy of M0ses

### PR DESCRIPTION
**Pull request by rytilahti**
Obsoletes #194

### CODE REVIEW

**Comment by M0ses** [comment]
LGTM, but maybe adding my test cases in an adapted version would make sense and could avoid regressions

**Comment by rytilahti** [comment]
Good point! I renamed the file (hopefully there'll be more tests for that part of the code) and changed test to assert with 'is' instead of '=='. Thanks for the patch!

**Comment by M0ses** [comment]
Thanks for fixing.

Just some nitpicking: Wouldn`t it make sense to change https://github.com/rytilahti/python-miio/pull/198/files#diff-57c62bdfa1f30df2fde08081703b47c5R5 to

```
assert validate_token(None, None, None) is None
```

as done below in https://github.com/rytilahti/python-miio/pull/198/files#diff-57c62bdfa1f30df2fde08081703b47c5R9 to be more consistent in coding?

BTW: I built rpm packages for openSUSE https://build.opensuse.org/project/show/home:M0ses:miio for those who want to try it on tumbleweed

**Comment by rytilahti** [comment]
Yeah, I think it would have made sense to compare both to is None, considering that "not" doesn't compare to Noneness but to trueness/falseness. That can probably be fixed at some point when new tests get added to that suite, I think it's not worth to change it for now.

Thanks for the packaging! If you want, the README could be updated to point to available packaging, I think archlinux has also a package available :-)

**Pull request merged**
