### PR TITLE
[WIP] zone cleaning

### PR DESCRIPTION
**Pull request by thelittlefireman**
Initial support of zone cleaning for gen2.
ref : [https://github.com/marcelrv/XiaomiRobotVacuumProtocol/blob/master/app_zoned_clean.md](https://github.com/marcelrv/XiaomiRobotVacuumProtocol/blob/master/app_zoned_clean.md)

TODO : 
- Test in real
- Find a way to get parameters easly
- Test on gen 1 ? (will it work ?)
- Get the spécific : "stop zone cleaning function"

### CODE REVIEW

**Comment by rytilahti** [comment]
Hi and thanks for working on this! It will not work on gen1 (without a modified firmware, that is), and I'm not sure how one can get those coordinates (I assume they are extracted from a map which has to be created beforehand).

Do you have a gen2 vacuum by yourself? It'd be nice to test it a bit before merging (as you also stated in your todo).

**Comment by thelittlefireman** [comment]
Hi,
My question for gen 1 was just if Xiaomi use the same firmware for both version: does they plan to implement the function in gen 1 and just add it to gen 2 for marketing benefits?

Yes I've got a gen 2 and a gen 1:) of course I planed to do some wireshark investigation and test by the end of the week I hope.

Sorry for my poor English =s

**Comment by itelli** [comment]
@thelittlefireman Did you investigate further for the zone cleaning? 

Can i provide any help?

**Comment by thelittlefireman** [comment]
Thanks,
I've no time for now to investigate (i hope later) and it seems to need further improvement to work correctly :
[https://github.com/marcelrv/XiaomiRobotVacuumProtocol/issues/1](https://github.com/marcelrv/XiaomiRobotVacuumProtocol/issues/1)

moreover, the map not have always the same orientation and so it cannot be possible to send the same coordinates same twice or more.

I hope xiaomi plan to add periodic zone cleaning in his app (like actual) periodic cleaning)

**Comment by olskar** [comment]
some users report that v1 now has support for zone cleaning @rytilahti :)

https://imgur.com/a/0Cqjz

**Comment by thelittlefireman** [comment]
#310

**Pull request closed without merging**
