### PR TITLE
Support for dmaker.fan.p11

### PR DESCRIPTION
**Pull request by swim2sun**
1. Refactor FanMiot code. 
2. Support `dmaker.fan.p11`

### CODE REVIEW

**Comment by swim2sun** [comment]
hi, @rytilahti I don't know how to fix the pipeline, the test is passed in my local environment 😥, could you help to review the code?

**Comment by iquix** [comment]
One reason that new code fails to run in Windows is that
filename in the miot_specs contains ':' (colon), which is not allowed in Windows filesystem.
(I had that problem while testing your code, when I was repackaging your whl file in Windows)

**Comment by iquix** [comment]
I'm not sure that it will pass the test, but my suggestion is

1. 
In the miot_spec_v2.py line 203, instead of 
     from . import miot_specs
you can try
    import miio.miot_specs

2.
add a blank __init__.py file in miot_specs directory

**Comment by swim2sun** [comment]
@iquix not working ;(

**Comment by syssi** [comment]
```
________________________________________________________________________________________________________ ERROR collecting miio/tests/test_airconditioningcompanion.py _________________________________________________________________________________________________________
../.cache/pypoetry/virtualenvs/python-miio-S_yPVV_M-py3.6/lib/python3.6/site-packages/dataclasses_json/core.py:263: in _decode_generic
    res = _get_type_cons(type_)(xs)
../.cache/pypoetry/virtualenvs/python-miio-S_yPVV_M-py3.6/lib/python3.6/site-packages/dataclasses_json/core.py:307: in <genexpr>
    for x in xs)
../.cache/pypoetry/virtualenvs/python-miio-S_yPVV_M-py3.6/lib/python3.6/site-packages/dataclasses_json/core.py:200: in _decode_dataclass
    elif _is_supported_generic(field_type) and field_type != str:
../.cache/pypoetry/virtualenvs/python-miio-S_yPVV_M-py3.6/lib/python3.6/site-packages/dataclasses_json/core.py:238: in _is_supported_generic
    type_) or is_union_type(type_) or is_enum
../.cache/pypoetry/virtualenvs/python-miio-S_yPVV_M-py3.6/lib/python3.6/site-packages/dataclasses_json/utils.py:92: in _is_optional
    _hasargs(type_, type(None)) or
../.cache/pypoetry/virtualenvs/python-miio-S_yPVV_M-py3.6/lib/python3.6/site-packages/dataclasses_json/utils.py:49: in _hasargs
    res = all(arg in type_.__args__ for arg in args)
../.cache/pypoetry/virtualenvs/python-miio-S_yPVV_M-py3.6/lib/python3.6/site-packages/dataclasses_json/utils.py:49: in <genexpr>
    res = all(arg in type_.__args__ for arg in args)
E   TypeError: argument of type 'NoneType' is not iterable
```

It looks like you hit this issue: https://github.com/lidatong/dataclasses-json/issues/232

Can be reproduced locally if you run the tests with python 3.6.

**Comment by swim2sun** [comment]
dmaker.fan.p11 is supported by https://github.com/rytilahti/python-miio/pull/850

**Pull request closed without merging**
