### PR TITLE
bump to 0.3.2, add RELEASING.md for describing the process

### PR DESCRIPTION
**Pull request by rytilahti**

### CODE REVIEW

**Comment by rytilahti** [comment]
@pluehne if you want, you can also check this out to see if everything's fine for a new release :-)

**Comment by pluehne** [comment]
@rytilahti: That’ll be a quick one for me. Let me check 😃.

**Comment by pluehne** [comment]
I was able to confirm that this now works perfectly, and my patch isn’t required anymore. Looks good to me for releasing 0.3.2. Thanks 😃!

**Comment by rytilahti** [comment]
Ok, thanks, let's release it!

**Comment by rytilahti** [comment]
Released https://pypi.python.org/pypi/python-miio .

**Comment by pluehne** [comment]
@rytilahti: Thanks! Could you also make a GitHub release tag? That would be useful for my AUR package, which builds against github.com 🙂.

**Comment by rytilahti** [comment]
@pluehne thanks for pointing that out! It's embarrassing to forgot pushing the tag (I don't do "github releases", just push git tags for releases) considering that I just added the RELEASING.md file in this PR...

**Comment by pluehne** [comment]
Pushing the Git tag was all I needed, many thanks again 😃!

**Comment by pluehne** [comment]
@rytilahti: I just packaged [`python-miio` 0.3.2 for Arch Linux](https://aur.archlinux.org/packages/python-miio/) in the AUR 🎉.

And thanks to @bluec0re’s help, I could now add a clean [Arch package for `android-backup-tools` 0.1.0](https://aur.archlinux.org/packages/python-android-backup-tools/) to the AUR and make this a proper dependency for `python-miio`.

This seems to be working very smoothly now 🙂.

**Pull request merged**
