### PR TITLE
Bump construct version (Closes: #374)

### PR DESCRIPTION
**Pull request by syssi**

### CODE REVIEW

**Comment by syssi** [comment]
https://github.com/home-assistant/home-assistant/pull/16362

**Comment by fabaff** [comment]
Any progress on this?

**Comment by rytilahti** [comment]
I have not yet tested this, but assuming everything keeps still working I'm all for merging it. I'll do test my devices later this week, @syssi has apparently already verified that this is working with his.

**Comment by rytilahti** [comment]
I did a test with the most recent construct version and everything I have (vacuum, powerstrip) kept working, so I removed the pinning for the next release!

**Comment by syssi** [comment]
Closing this because we dropped the pin. cp. #384

**Pull request closed without merging**
