### PR TITLE
gateway: fix zigbee lights

### PR DESCRIPTION
**Pull request by starkillerOG**
fix zigbee lights, for more info see https://github.com/home-assistant/core/issues/48988

### CODE REVIEW

**Review by rytilahti — APPROVED** [review]
I presume these never worked before, right? Or could this be a breaking change for some existing lights?

Other than that, looks good to me!

**Comment by starkillerOG** [comment]
@rytilahti no they probably have newer worked.
I added them, but I don't own them, so I could not test.

Together with a user we have now tested it and now we know which commands work.
He has not tested the exact code of this PR, but the commands schould work.

**Comment by rytilahti** [comment]
Okay, so this can be merged now, or do you want to wait for a confirmation from the user?

**Comment by starkillerOG** [comment]
@rytilahti @xekil already tested it and has confirmed this PR works.
This can now be merged.

**Comment by xekil** [comment]
any idea when the HA update is available that includes this fix?

**Pull request merged**
