### PR TITLE
WIP: Initial support for Vacuum 1C STYTJ01ZHM (dreame.vacuum.mc1808)

### LINKED ISSUE #669: Add support for Vacuum 1C STYTJ01ZHM
WARNING:miio.discovery:Found unsupported device dreame-vacuum-mc1808_miio29430xxxx._miio._udp.local. at 192.168.0.172, please report to developers

would love to get support :)

### PR DESCRIPTION
**Pull request by rytilahti**
Partially autogenerated based on the spec file, so things may or may not work,
so use at your own risk. in its current state it is more or less just for testing.

Fixes #669 when its ready.
This based itself on #672, so it should be merged first when the time comes.

### CODE REVIEW

**Comment by craiq** [comment]
requests are using 'get_prop' but should be 'get_properties'

**Comment by craiq** [comment]
Start
action "{'did':'...','siid':18,'aiid':1,'in':[{'piid':1,'value':2}]}"

Resume to charge
action "{'did':'...','siid':2,'aiid':1,'in':[]}"

**Comment by floman321** [comment]
hello, what syntax should a use for start_remote please ? X and Y ?

**Comment by craiq** [comment]
start_remote will just start the modus without additional variables
Then you have to give direction and speed as separate commands. But they are not integrated yet

**Comment by floman321** [comment]
thanks you

**Comment by floman321** [comment]
this is working well. thank you for your work.

**Comment by Concentricc** [comment]
@rytilahti would you mind to explain how the commands are working.
Mainly the siid piid and aiid.
Im interested in seeing if i can create some more commands.
Thanks

**Comment by rytilahti** [comment]
Do you have something specific you are interested in?

The code itself bases on the metadata files that are available on the internet (https://github.com/rytilahti/python-miio/issues/543#issuecomment-544643792) which are parsed using the script found under `devtools` directory of the repository. https://github.com/rytilahti/python-miio/issues/543#issuecomment-544745035 describes the different pieces of information found in those description files.

The PR linked on the issue description (#672) which this bases on has some todo items. For example, the manual controls on this device are done using writing the properties of the service with siid 21 (https://github.com/rytilahti/python-miio/pull/683/files#diff-1d60d6cac3e7d3a87e527874901056afR195). 

About setting properties, the API is not yet there, but you can get an idea if you take a look at https://github.com/rytilahti/python-miio/pull/672/files#diff-917e6e7e59bfa94f83c5923372d51a4dR32 . The `state` here is the property as listed in the dataclass defined by `_MAPPING`, so setting the fan speed to silent should probably work by doing:
```
vac.set_property(fan_speed=0)
```

For actions, the service id and action id are also obtained from the description file.

**Comment by Concentricc** [comment]
Thanks for the info
Im looking for an explanation of implementing the API rather than using it.
Such as:
`@command()
    def stop_sweeping(self) -> None:
        """aiid 2 Stop Sweeping: in: [] -> out: []"""
        return self.call_action(3, 2)` 

From what i can make out for each action requires a call to `call_action` with a siid, aiid and an optional payload.

I was attempting to change the fan speed with something like the following:
`@command()
    def fan_speed(self) -> None:
        payload = [{"piid": 6, "value": 3}]
        return self.call_action(6,2,payload)`

**Comment by rytilahti** [comment]
Where did you get the siid 6, aiid 2 for the call? Anyways, if you look at the description file, the fan speed is a property as I mentioned above. Did you try that `set_property` method call?

So maybe something like this could work?
```
@command(
    click.argument("speed", type=EnumType(VacuumSpeed, casesensitive=False))
)
def fan_speed(self, speed):
    return self.set_property(fan_speed=speed.value)
```

and calling like `fan_speed silent` with any `VacuumSpeed`.

**Comment by Concentricc** [comment]
I think i have a clearer picture now of how this works.
One last thing, I _think_ with the mapping.
A simple function like this:
` @command()
    def fan_speed(self):
        return self.set_property(fan_speed=3)`
should turn the vacuum speed to turbo.
However it requires arguments for each property.
https://pastebin.com/xPPB687y

Thanks again for explaining

**Comment by rytilahti** [comment]
Ah, indeed, I didn't recall that API is not yet complete, sorry for that. To make it work, all the field definitions need to be modified to default to some value.

So 
```
battery: int = field(metadata={"siid": 2, "piid": 1, "access": ["read", "notify"]})
```
needs to become
```
battery: int = field(metadata={"siid": 2, "piid": 1, "access": ["read", "notify"]}, default=None)
```
and so on for each and every field.

This is related to the TODO item `helper to create fields with wanted metadata, maybe add_property(piid, siid)?`.

**Comment by Concentricc** [comment]
I had to add the `default=None` to each property, but then then finally got it working.
`@command(click.argument("speed", type=int))
    def fan_speed(self, speed):
        return self.set_property(fan_speed=speed)`
What further work needs to be done to get this merged(at least basic functionality)?
Im keen on getting a home assistant integration for this

**Comment by rytilahti** [comment]
So there are two things that needs to be done until I'm satisfied to get this out:
1. Improve the miot API implementation for cleaner action calls, setters. When I find some time I will be working on this.
2. Generalize the vacuum interface (https://github.com/rytilahti/python-miio/issues/669#issuecomment-625879953) so that all different vacuums can be controlled using a common interface.

**Comment by Griizly** [comment]
Hello, stupid question, is it already possible to install this on home assistant ?

**Comment by SLG** [comment]
@rytilahti I'm new to this repo, but have both Home Assistant as a Vacuum 1c. Is there anything I can do to help? I've just created a simple cli file, based on the vacuum_cli, but a lot of commands are still missing.
@Griizly , nope, not until this PR is merged.

**Comment by rytilahti** [comment]
@SLG see my previous comment (the link). We are going to need an abstract interface (or interfaces, the status containers should also have a common base) that exposes the common functionality of all current (and potential future) implementations. The vacuum implementations will implement this interface and we can simply use the common interface in homeassistant (or cli) to provide some basic functionality using that interface.

**Comment by craiq** [comment]
does anyone has a working fork for just this vacuum?
I would love to use the vacuum with home assistant in the near future.

**Comment by Concentricc** [comment]
> does anyone has a working fork for just this vacuum?
> I would love to use the vacuum with home assistant in the near future.

https://github.com/Concentricc/xiaomi_vacuum
It has the basic features working.
Spot cleaning/ room cleaning and other more advanced features dont work. (dont know if they are supported.)

**Comment by craiq** [comment]
great!!! Thank you! I'll have a look :)

**Review by htmltiger — APPROVED** [review]

**Comment by muchar** [comment]
+1

**Comment by rytilahti** [comment]
This has been obsoleted by #952.

**Pull request closed without merging**
